import Head from 'next/head'
import '../components/MySearchBar.css'


function MyApp({ Component, pageProps }) {
  return <div className='container'>
    <Head>
    <div >
      <title >트렌드 분석 시스템 </title>
      </div>

      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"/>
      <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
        crossOrigin="anonymous"/>
        <link href='/style.css' rel='stylesheet'/>
    </Head>
    <Component {...pageProps} />
  </div>
}

export default MyApp
